spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/spring?characterEncoding=UTF-8&serverTimezone=UTC
    username: HC-5514
    password: 5514
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
